### ISSUE TITLE
Error installing ‘oraclejdk8’: “Expected feature release number in range of 9 to 14, but got: 8”

### ISSUE THREAD

**Issue by josd** [bdevloed/eye#1]
Boris, we currently get the same issue as mentioned in https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/9
and I was wondering whether adding dist: trusty to .travis.yml would help in our case?

**Comment by bdevloed** [comment]
Hi Jos, I've created a pull request for your project.
I've already successfully applied the same changes to the travis downstream trigger for this project in https://github.com/bdevloed/eye/commit/994625fb65eae11b6aca1298521e171c55a211cb#diff-354f30a63fb0907d4ad57269548329e3

**Comment by bdevloed** [comment]
Fixed in josd/eye
